include ../../../config/Makefile

CC = $(BYTECC)
CFLAGS = -c -I./h -DCAML_LIGHT
KERNH = h/BigNum.h 
OBJS = o/KerN.$(O) o/bnInit.$(O) o/bnMult.$(O) o/bnDivide.$(O) \
       o/bnCmp.$(O) o/bzf.$(O) o/bz.$(O) 

all: dbignum.$(A) sbignum.$(A)

scratch:
	rm -f *.$(A) o/*.$(O)

# DLL

dbignum.$(A): $(OBJS:.$(O)=.$(DO))
	$(call MKLIB,dbignum.$(A),$(OBJS:.$(O)=.$(DO)))

o/KerN.$(DO): c/KerN.c 
	$(CC) $(CFLAGS) $(DLLCCCOMPOPTS) c/KerN.c
	mv KerN.$(O) o/KerN.$(DO)

o/bnInit.$(DO): c/bn/bnInit.c $(KERNH)
	$(CC) $(CFLAGS) $(DLLCCCOMPOPTS) c/bn/bnInit.c
	mv bnInit.$(O) o/bnInit.$(DO)

o/bnMult.$(DO): c/bn/bnMult.c $(KERNH)
	$(CC) $(CFLAGS) $(DLLCCCOMPOPTS) c/bn/bnMult.c
	mv bnMult.$(O) o/bnMult.$(DO)

o/bnDivide.$(DO): c/bn/bnDivide.c $(KERNH)
	$(CC) $(CFLAGS) $(DLLCCCOMPOPTS) c/bn/bnDivide.c
	mv bnDivide.$(O) o/bnDivide.$(DO)

o/bnCmp.$(DO): c/bn/bnCmp.c $(KERNH)
	$(CC) $(CFLAGS) $(DLLCCCOMPOPTS) c/bn/bnCmp.c
	mv bnCmp.$(O) o/bnCmp.$(DO)

o/bz.$(DO): c/bz.c h/BigZ.h $(KERNH)
	$(CC) $(CFLAGS) $(DLLCCCOMPOPTS) c/bz.c
	mv bz.$(O) o/bz.$(DO)

o/br.$(DO): c/br.c h/BigR.h h/BigZ.h $(KERNH)
	$(CC) $(CFLAGS) $(DLLCCCOMPOPTS) c/br.c
	mv br.$(O) o/br.$(DO)

o/bzf.$(DO): c/bzf.c h/BigZ.h $(KERNH)
	$(CC) $(CFLAGS) $(DLLCCCOMPOPTS) c/bzf.c
	mv bzf.$(O) o/bzf.$(DO)

# Static

sbignum.$(A): $(OBJS:.$(O)=.$(SO))
	$(call MKLIB,sbignum.$(A),$(OBJS:.$(O)=.$(SO)))

o/KerN.$(SO): c/KerN.c 
	$(CC) $(CFLAGS) $(BYTECCCOMPOPTS) c/KerN.c
	mv KerN.$(O) o/KerN.$(SO)

o/bnInit.$(SO): c/bn/bnInit.c $(KERNH)
	$(CC) $(CFLAGS) $(BYTECCCOMPOPTS) c/bn/bnInit.c
	mv bnInit.$(O) o/bnInit.$(SO)

o/bnMult.$(SO): c/bn/bnMult.c $(KERNH)
	$(CC) $(CFLAGS) $(BYTECCCOMPOPTS) c/bn/bnMult.c
	mv bnMult.$(O) o/bnMult.$(SO)

o/bnDivide.$(SO): c/bn/bnDivide.c $(KERNH)
	$(CC) $(CFLAGS) $(BYTECCCOMPOPTS) c/bn/bnDivide.c
	mv bnDivide.$(O) o/bnDivide.$(SO)

o/bnCmp.$(SO): c/bn/bnCmp.c $(KERNH)
	$(CC) $(CFLAGS) $(BYTECCCOMPOPTS) c/bn/bnCmp.c
	mv bnCmp.$(O) o/bnCmp.$(SO)

o/bz.$(SO): c/bz.c h/BigZ.h $(KERNH)
	$(CC) $(CFLAGS) $(BYTECCCOMPOPTS) c/bz.c
	mv bz.$(O) o/bz.$(SO)

o/br.$(SO): c/br.c h/BigR.h h/BigZ.h $(KERNH)
	$(CC) $(CFLAGS) $(BYTECCCOMPOPTS) c/br.c
	mv br.$(O) o/br.$(SO)

o/bzf.$(SO): c/bzf.c h/BigZ.h $(KERNH)
	$(CC) $(CFLAGS) $(BYTECCCOMPOPTS) c/bzf.c
	mv bzf.$(O) o/bzf.$(SO)

