#!/usr/local/bin/perl
# Insert Next/Previous/Contents buttons in a set of pages.

@pages = sort fragmentorder @ARGV;

sub fragmentorder {
  $a =~ /^node([0-9]+)/; $na = $1;
  if ($a =~ /^node[0-9]+\.([0-9]+)\.html/) { $fa = $1; } else { $fa = 0; }
  $b =~ /^node([0-9]+)/; $nb = $1;
  if ($b =~ /^node[0-9]+\.([0-9]+)\.html/) { $fb = $1; } else { $fb = 0; }
  return (($na <=> $nb) || ($fa <=> $fb));
}

for ($i = 0; $i <= $#pages; $i++) {
  open(SRC, $pages[$i]);
  open(DST, "> newpage.html");
  select(DST);
  $_ = <SRC>;   # Title line
  print "<HEAD>\n";
  print $_;
  print "</HEAD>\n";
  print "<BODY>\n";
  if ($i < $#pages) {
    print '<A HREF="', $pages[$i+1], '"><IMG SRC="next_motif.gif"></A>', "\n";
  }
  if ($i > 0) {
    print '<A HREF="', $pages[$i-1], '"><IMG SRC="previous_motif.gif"></A>', "\n";
  }
  print '<A HREF="index.html"><IMG SRC="contents_motif.gif"></A>', "\n";
  print "<HR>\n";
  $numlines = 0;
  while (<SRC>) {
    $numlines++;
    print $_;
  }
  if ($numlines >= 40) {
    print "<HR>\n";
    if ($i < $#pages) {
      print '<A HREF="', $pages[$i+1], '"><IMG SRC="next_motif.gif"></A>', "\n";
    }
    if ($i > 0) {
      print '<A HREF="', $pages[$i-1], '"><IMG SRC="previous_motif.gif"></A>', "\n";
    }
    print '<A HREF="index.html"><IMG SRC="contents_motif.gif"></A>', "\n";
  }
  close(SRC);
  close(DST);
  rename("newpage.html", $pages[$i]);
}
