(* TEST
 flags = "-I ${ocamlsrcdir}/typing -I ${ocamlsrcdir}/parsing";
 include ocamlcommon;
 expect;
 *)


let expr mapper (e : Parsetree.expression) =
  let open Parsetree in
  let e = match e.pexp_desc with
    | Pexp_extension ({txt=("metaocaml.escape"|"metaocaml.bracket") as name},p) ->
       (* Here we make the extension node look like it was generated by
          the [metaocaml_expr] parser rules. *)
       { e with pexp_desc = Pexp_extension (Location.mknoloc name,p) }
    | _ -> e
  in
  Ast_mapper.default_mapper.expr mapper e

let run s =
  let s = Parse.implementation (Lexing.from_string s) in
  let mapper = { Ast_mapper.default_mapper with expr } in
  let s = mapper.structure mapper s in
  Format.printf "%a@." Pprintast.structure s
;;

[%%expect{|
val expr : Ast_mapper.mapper -> Parsetree.expression -> Parsetree.expression =
  <fun>
val run : string -> unit = <fun>
|}];;

run {|
let rec spower n x =
  if n = 0 then [%metaocaml.bracket 1]
  else if n mod 2 = 0 then
    [%metaocaml.bracket square [%metaocaml.escape spower (n/2) x]]
  else
    [%metaocaml.bracket [%metaocaml.escape x] * [%metaocaml.escape spower (n-1) x]]
|}

[%%expect{|
let rec spower n x =
  if n = 0
  then .< 1 >.
  else
    if (n mod 2) = 0
    then .< square .~(spower (n / 2) x) >.
    else .< .~x * .~(spower (n - 1) x) >.
- : unit = ()
|}];;
