#!/bin/sh
#########################################################################
#                                                                       #
#                                OCaml                                  #
#                                                                       #
#            Xavier Leroy, projet Cristal, INRIA Rocquencourt           #
#                    Mark Shinwell, Jane Street Europe                  #
#                                                                       #
#   Copyright 2004, 2015 Institut National de Recherche en Informatique #
#   et en Automatique.  All rights reserved.  This file is distributed  #
#   under the terms of the GNU Library General Public License, with     #
#   the special exception on linking described in file ../LICENSE.      #
#                                                                       #
#########################################################################

case $1 in
    asmcomp/clambdagen.* \
  | asmcomp/flambdaexport.* \
  | asmcomp/flambdaexport_types.* \
  | asmcomp/flambdasym.* \
  | asmcomp/import_approx.* \
  | middle_end/*)
    # Strict compilation options for Flambda passes.
    # Constructor/record field disambiguation is kept in check by
    # using -principal (which is also morally correct).
    echo '-w +a-4-9+27-30-40-41-42 -principal -safe-string -strict-formats'
    ;;
esac
