#!/bin/sh
#########################################################################
#                                                                       #
#                                OCaml                                  #
#                                                                       #
#            Xavier Leroy, projet Cristal, INRIA Rocquencourt           #
#                    Mark Shinwell, Jane Street Europe                  #
#                                                                       #
#   Copyright 2004, 2015 Institut National de Recherche en Informatique #
#   et en Automatique.  All rights reserved.  This file is distributed  #
#   under the terms of the GNU Library General Public License, with     #
#   the special exception on linking described in file ../LICENSE.      #
#                                                                       #
#########################################################################

case $1 in
    middle_end/abstract_identifiers.* \
  | middle_end/closure_conversion.* \
  | middle_end/effect_analysis.* \
  | middle_end/flambdacheck.* \
  | middle_end/flambdaiter.* \
  | middle_end/flambda.* \
  | middle_end/flambdasimplify.* \
  | middle_end/flambdasubst.* \
  | middle_end/flambdautils.* \
  | middle_end/inconstant_idents.* \
  | middle_end/inlining_cost.* \
  | middle_end/inlining_decision.* \
  | middle_end/inlining_env.* \
  | middle_end/inlining.* \
  | middle_end/inlining_result.* \
  | middle_end/inlining_stats.* \
  | middle_end/inlining_stats_types.* \
  | middle_end/invariant_params.* \
  | middle_end/printflambda.* \
  | middle_end/ref_to_variables.* \
  | middle_end/simple_value_approx.* \
  | middle_end/symbol.*\
  | asmcomp/clambdagen.* \
  | asmcomp/flambdaexport.* \
  | asmcomp/flambdasym.*)
    # More aggressive "unused identifier" warnings for Flambda passes.
    # Also suppress "label ... defined in both ..." for record types, since
    # it is of no consequence.
    echo '-w +K+27-30'
    ;;
esac
