#!/bin/sh

#########################################################################
#                                                                       #
#                                G'Caml                                 #
#                                                                       #
#                    Jun Furuse, University of Tokyo                    #
#                                                                       #
#   Copyright 2005 Institut National de Recherche en Informatique et    #
#   en Automatique.  All rights reserved.  This file is distributed     #
#   under the terms of the GNU Library General Public License, with     #
#   the special exception on linking described in file ../LICENSE.      #
#                                                                       #
#########################################################################

boot/ocamlrun ./ocaml -I stdlib -I toplevel -I gcamllib $*
