#**************************************************************************
#*                                                                        *
#*                                 OCaml                                  *
#*                                                                        *
#*                David Allsopp, MetaStack Solutions Ltd.                 *
#*                                                                        *
#*   Copyright 2017 MetaStack Solutions Ltd.                              *
#*                                                                        *
#*   All rights reserved.  This file is distributed under the terms of    *
#*   the GNU Lesser General Public License version 2.1, with the          *
#*   special exception on linking described in the file LICENSE.          *
#*                                                                        *
#**************************************************************************

include $(ROOTDIR)/config/Makefile

$(ROOTDIR)/byterun/caml/s.h caml/s.h: $(ROOTDIR)/config/s.h
	cp $^ $@

$(ROOTDIR)/byterun/caml/m.h caml/m.h: $(ROOTDIR)/config/m.h
	cp $^ $@
