### Compile-time configuration

### Name of architecture for the native-code compiler
### Currently supported: alpha, sparc, i386
### Set ARCH=none if your machine is not supported
ARCH=alpha
#ARCH=mips
#ARCH=sparc
#ARCH=i386
#ARCH=none

### Which C compiler to use for the bytecode interpreter.
### Performance of the bytecode interpreter is *much* improved
### if Gnu CC 2 is used.
BYTECC=gcc
#BYTECC=cc

### Additional compile-time options for $(BYTECC).
# If using gcc on Intel 386 or Motorola 68k:
# BYTECCCOMPOPTS=-fno-defer-pop
# If using gcc and being superstitious:
BYTECCCOMPOPTS=-Wall
# Otherwise:
# BYTECCCOMPOPTS=

### Which C compiler to use for the native-code compiler.
### cc is better than gcc on the Mips and Alpha.
NATIVECC=cc
#NATIVECC=gcc

### Additional compile-time options for $(NATIVECC).
# NATIVECCCOMPOPTS=
# For the Alpha:
NATIVECCCOMPOPTS=-std1

### Additional link-time options
CCLINKOPTS=

### If using GCC on a Dec Alpha under OSF1:
LOWADDRESSES=-Xlinker -taso
# Otherwise:
# LOWADDRESSES=

### Flags for the assembler
# For the Sparc:
# ASFLAGS=-P
# For the Alpha or the Mips:
ASFLAGS=-O2
# Otherwise:
# ASFLAGS=

### Libraries needed
CCLIBS=$(TERMINFOLIBS) -lm

### How to invoke ranlib (if needed)
# BSD-style:
RANLIB=ranlib
# System V-style:
# RANLIB=ar -rs
# If ranlib is not needed at all:
# RANLIB=true

### Do #! scripts work on your system?
SHARPBANGSCRIPTS=true
# SHARPBANGSCRIPTS=false

### Where to install the binaries
BINDIR=/usr/local/bin

### Where to install the standard library
LIBDIR=/usr/local/lib/camlsl

### Where to install the man pages
MANDIR=/usr/local/man/man1
MANEXT=1
