#**************************************************************************
#*                                                                        *
#*                                 OCaml                                  *
#*                                                                        *
#*            Xavier Leroy, projet Cristal, INRIA Rocquencourt            *
#*                                                                        *
#*   Copyright 1999 Institut National de Recherche en Informatique et     *
#*     en Automatique.                                                    *
#*                                                                        *
#*   All rights reserved.  This file is distributed under the terms of    *
#*   the GNU Lesser General Public License version 2.1, with the          *
#*   special exception on linking described in the file LICENSE.          *
#*                                                                        *
#**************************************************************************

# The main Makefile

include Makefile.shared

# The compilation of ocaml will fail if the runtime has changed.
# Never mind, just do make bootstrap to reach fixpoint again.

# Compile everything the first time
world: coldstart all

# Do a complete bootstrapping cycle
bootstrap:
	$(MAKEREC) coreboot
	$(MAKEREC) all
	$(MAKEREC) compare

# Compile the native-code compiler
opt-core:
	$(MAKEREC) runtimeopt
	$(MAKEREC) ocamlopt
	$(MAKEREC) libraryopt

opt:
	$(MAKEREC) opt-core
	$(MAKEREC) otherlibrariesopt ocamltoolsopt

# Native-code versions of the tools
# If the submodule is initialised, then opt.opt will build a native flexlink
opt.opt: core opt-core ocamlc.opt all ocamlopt.opt ocamllex.opt \
         ocamltoolsopt ocamltoolsopt.opt otherlibrariesopt $(OCAMLDOC_OPT) \
         $(if $(wildcard flexdll/Makefile),flexlink.opt)

# Complete build using fast compilers
world.opt: coldstart opt.opt

runtop:
	$(MAKEREC) core
	$(MAKEREC) ocaml
	@rlwrap --help 2>/dev/null && $(EXTRAPATH) rlwrap $(RUNTOP) || $(EXTRAPATH) $(RUNTOP)

natruntop:
	$(MAKEREC) runtime
	$(MAKEREC) coreall
	$(MAKEREC) opt.opt
	$(MAKEREC) ocamlnat
	@rlwrap --help 2>/dev/null && $(EXTRAPATH) rlwrap $(NATRUNTOP) || $(EXTRAPATH) $(NATRUNTOP)

.PHONY: bootstrap
.PHONY: opt-core opt opt.opt
.PHONY: world world.opt

include .depend
