# Makefile for the portable graphics library

!include ..\..\config\Makefile.nt

CAMLC=..\..\boot\ocamlrun ..\..\boot\ocamlc -I ..\..\boot
CAMLOPT=..\..\boot\ocamlrun ..\..\ocamlopt -I ..\..\stdlib

all: graphics.cmi graphics.cmo

allopt:

partialclean:
	rm -f *.cm*

clean: partialclean

install:
	cp graphics.cm[io] $(LIBDIR)

installopt:

.SUFFIXES: .ml .mli .cmo .cmi .cmx

.mli.cmi:
	$(CAMLC) -c $<
.ml.cmo:
	$(CAMLC) -c $<
.ml.cmx:
	$(CAMLOPT) -c $(COMPFLAGS) $<

depend:
	..\..\tools\ocamldep *.mli *.ml >> .depend

!include .depend
