
MODULES=misc warnings config identifiable numbers arg_helper clflags terminfo
MODULES+=location docstrings lexer syntaxerr ast_helper longident parser parse
ADD_COMPFLAGS=-I $(OTOPDIR)/utils -I $(OTOPDIR)/parsing

include $(BASEDIR)/makefiles/Makefile.several
include $(BASEDIR)/makefiles/Makefile.common
