(**************************************************************************)
(*                                                                        *)
(*                                 OCaml                                  *)
(*                                                                        *)
(*                Ulysse Gérard, Thomas Refis, Frederic Bour,             *)
(*                           Xavier Van de Woestyne                       *)
(*                                                                        *)
(*   Copyright 2025 Tarides                                               *)
(*                                                                        *)
(*   All rights reserved.  This file is distributed under the terms of    *)
(*   the GNU Lesser General Public License version 2.1, with the          *)
(*   special exception on linking described in the file LICENSE.          *)
(*                                                                        *)
(**************************************************************************)

(** Extend the given attributes with an incorrect attribute and the
    saved types after turning them into attributes *)
val recovery_attributes : Parsetree.attributes -> Parsetree.attributes


(** [with_saved_types ?save_part f] run [f] with a fresh empty saved-types
    buffer, then optionally (with [save_part]) save one derived value
    back into the previous buffer. *)
val with_saved_types :
  ?save_part:('a -> Cmt_format.binary_part) -> (unit -> 'a) -> 'a

(** Check whether an expression was generated by the recovery. *)
val erroneous_expr_check : Typedtree.expression -> bool

(** Retrieve saved types that were turned into attributes. *)
val get_saved_types_from_attributes :
  Parsetree.attributes -> Cmt_format.binary_part list
