(**************************************************************************)
(*                                                                        *)
(*                                 OCaml                                  *)
(*                                                                        *)
(*                Ulysse Gérard, Thomas Refis, Frederic Bour,             *)
(*                           Xavier Van de Woestyne                       *)
(*                                                                        *)
(*   Copyright 2025 Tarides                                               *)
(*                                                                        *)
(*   All rights reserved.  This file is distributed under the terms of    *)
(*   the GNU Lesser General Public License version 2.1, with the          *)
(*   special exception on linking described in the file LICENSE.          *)
(*                                                                        *)
(**************************************************************************)

(** {1 Logging and raising}

    The main mechanism of recovery involves choosing between logging or
    raising an error, using the [log_or_raise] and [log_and_raise].
    If the [-typing-recovery] flag is not present, both functions just raise
    an exception. *)

(** Returns a reference initially set to false that will be set to true
    when an error is logged (see below). *)
val monitor_errors : unit -> bool ref

(** [log_and_raise exn] raises [exn], but also logs it when called from
    under [catch_errors]. *)
val log_and_raise : exn -> 'a

(** Logs the given exception if called from under a [catch_errors]
    otherwise raises it. *)
val log_or_raise : exn -> unit

(** {1 Catching errors} *)

(** [catch_error errors_log f] gathers all the errors logged by [f ()] into
    [errors_log]. *)
val catch_errors : exn list ref -> (unit -> 'a) -> 'a

(** [uncatch_errors f] disables logging in f, turning both [log_or_raise] and
    [log_and_raise] into [raise]. *)
val uncatch_errors : (unit -> 'a) -> 'a

(** A callback for avoiding cyclic-dependencies. *)
val is_typemod_recoverable_error: (exn -> bool) ref

(** {1 Keep track of type variables generated by error recovery}

    When the recovery process introduces types, we record them to prevent
    cascading errors resulting from the introduction of those types. *)

(** Register a type generated by the recovery. *)
val erroneous_type_register : Types.type_expr -> unit

(** Check whether a type expression was generated by the recovery. *)
val erroneous_type_check : Types.type_expr -> bool

(** {1 Error Set}

    Since an error may be logged by the recovery handler but later
    clarified in another handler, we use a set to generate the list of
    errors to display to the user, overwriting errors that share the
    same location. *)

module Error_set : Set.S with type elt = Location.error
