#########################################################################
#                                                                       #
#                                 OCaml                                 #
#                                                                       #
#                 Xavier Clerc, SED, INRIA Rocquencourt                 #
#                                                                       #
#   Copyright 2010 Institut National de Recherche en Informatique et    #
#   en Automatique.  All rights reserved.  This file is distributed     #
#   under the terms of the Q Public License version 1.0.                #
#                                                                       #
#########################################################################

#MODULES=
MAIN_MODULE=tprintf
ADD_COMPFLAGS=-I $(BASEDIR)/lib
ADD_MODULES=testing

include ../../makefiles/Makefile.one
include ../../makefiles/Makefile.common
