include ../support/Makefile.common.nt

CCFLAGS=-I../support -I../../../byterun $(TK_DEFS)

COMPFLAGS=-I $(OTHERS)/win32unix -I ../support -I ../camltk

all: tkanim.cma dlltkanim.dll libtkanim.$(A)
opt: tkanim.cmxa libtkanim.$(A)
example: gifanimtest.exe

OBJS=tkanim.cmo
COBJS= cltkaniminit.obj tkAnimGIF.obj
DCOBJS=$(COBJS:.obj=.$(DO))
SCOBJS=$(COBJS:.obj=.$(SO))

tkanim.cma: $(OBJS)
	$(CAMLLIBR) -o tkanim.cma $(OBJS) \
	  -dllib -ltkanim -cclib -ltkanim -cclib "$(TK_LINK)"

tkanim.cmxa: $(OBJS:.cmo=.cmx)
	$(CAMLOPTLIBR) -o tkanim.cmxa $(OBJS:.cmo=.cmx) \
	  -cclib -ltkanim -cclib "$(TK_LINK)"

libtkanim.$(A): $(SCOBJS)
	$(call MKLIB,libtkanim.$(A), $(SCOBJS))

dlltkanim.dll: $(DCOBJS)
	$(call MKDLL,dlltkanim.dll,tmp.$(A), \
	  $(DCOBJS) ../support/dll$(LIBNAME).$(A) \
	  ../../../byterun/ocamlrun.$(A) \
	  $(TK_LINK) $(call SYSLIB,wsock32))
	rm tmp.*

gifanimtest.exe: all gifanimtest.cmo
	$(CAMLC) -custom -o $@ -I ../lib -I ../camltk -I ../support unix.cma $(LIBNAME).cma tkanim.cma gifanimtest.cmo

# animwish: $(TKANIM_LIB) tkAppInit.o
# 	$(CC) -o $@  tkAppInit.o $(TK_LINK) $(X11_LINK) \
# 		-L. -ltkanim $(LIBS)

clean:
	rm -f *.cm* *.$(O) *.$(A) *.dll gifanimtest.exe

$(OBJS) $(OBJS:.cmo=.cmi): ../lib/$(LIBNAME).cma

$(OBJS:.cmo=.cmx): ../lib/$(LIBNAME).cmxa

.SUFFIXES :
.SUFFIXES : .mli .ml .cmi .cmo .mlp .cmx .c .$(DO) .$(SO)

.mli.cmi:
	$(CAMLCOMP) $(COMPFLAGS) $<

.ml.cmo:
	$(CAMLCOMP) $(COMPFLAGS) $<

.ml.cmx:
	$(CAMLOPT) -c $(COMPFLAGS) $<

.c.$(DO):
	$(BYTECC) $(DLLCCCOMPOPTS) $(CCFLAGS) -c $<
	mv $*.$(O) $*.$(DO)

.c.$(SO):
	$(BYTECC) $(BYTECCCOMPOPTS) $(CCFLAGS) -c $<
	mv $*.$(O) $*.$(SO)

install: tkanim.cma 
	cp dlltkanim.dll $(STUBLIBDIR)/dlltkanim.dll
	cp tkanim.cma *.cmi *.mli libtkanim.$(A) $(INSTALLDIR)

installopt: tkanim.cmxa
	cp tkanim.cmxa tkanim.$(A) $(INSTALLDIR)

depend: tkanim.ml
	$(CAMLDEP) *.mli *.ml > .depend

include .depend
