#########################################################################
#                                                                       #
#                            Objective Caml                             #
#                                                                       #
#            Xavier Leroy, projet Cristal, INRIA Rocquencourt           #
#                                                                       #
#   Copyright 1999 Institut National de Recherche en Informatique et    #
#   en Automatique.  All rights reserved.  This file is distributed     #
#   under the terms of the GNU Library General Public License, with     #
#   the special exception on linking described in file ../../../LICENSE.#
#                                                                       #
#########################################################################

# $Id$

include ../../../config/Makefile

CAMLC=../../../boot/ocamlrun ../../../ocamlc -I ../../../stdlib -I ..
CAMLOPT=../../../boot/ocamlrun ../../../ocamlopt -I ../../../stdlib -I ..
CC=$(BYTECC)
CFLAGS=-I.. $(BYTECCCOMPOPTS)

test: test.byt test.opt
	../../../byterun/ocamlrun -I .. ./test.byt
	./test.opt

TESTFILES=test.cmo \
  test_nats.cmo test_big_ints.cmo test_ratios.cmo test_nums.cmo \
  test_io.cmo end_test.cmo

TESTOPTFILES=$(TESTFILES:.cmo=.cmx)

test.byt: $(TESTFILES) ../nums.cma ../libnums.$(A)
	$(CAMLC) -o test.byt nums.cma $(TESTFILES)

test.opt: $(TESTOPTFILES) ../nums.cmxa ../libnums.$(A)
	$(CAMLOPT) -o test.opt nums.cmxa $(TESTOPTFILES)

test_bng.exe: test_bng.o
	$(CC) $(CFLAGS) -o test_bng.exe ../bng.o test_bng.o -lbignum

$(TESTOPTFILES): ../../../ocamlopt

.SUFFIXES: .ml .cmo .cmx

.ml.cmo:
	$(CAMLC) -c $<

.ml.cmx:
	$(CAMLOPT) -c $<

ocamltopnum.exe:
	ocamlmktop -o ocamltopnum.exe -custom ../nums.cma ../libnums.$(A)

clean:
	rm -f test.byt test.opt test_bng.exe *.$(O) *.cm? ocamltopnum.exe

depend:
	ocamldep *.ml > .depend

include .depend
