#########################################################################
#                                                                       #
#                            Objective Caml                             #
#                                                                       #
#            Xavier Leroy, projet Cristal, INRIA Rocquencourt           #
#                                                                       #
#   Copyright 1999 Institut National de Recherche en Informatique et    #
#   en Automatique.  All rights reserved.  This file is distributed     #
#   under the terms of the GNU Library General Public License, with     #
#   the special exception on linking described in file ../../../LICENSE.#
#                                                                       #
#########################################################################

# $Id$

CAMLC=..\..\..\boot\ocamlrun ..\..\..\ocamlc -I ..\..\..\stdlib -I ..
CAMLOPT=..\..\..\boot\ocamlrun ..\..\..\ocamlopt -I ..\..\..\stdlib -I ..

test: test.byt test.opt
	..\..\..\byterun\ocamlrun -I .. .\test.byt
	.\test.opt

TESTFILES=test.cmo \
  test_nats.cmo test_big_ints.cmo test_ratios.cmo test_nums.cmo \
  test_io.cmo end_test.cmo

TESTOPTFILES=$(TESTFILES:.cmo=.cmx)

test.byt: $(TESTFILES) ..\nums.cma ..\libnums.lib
	$(CAMLC) -o test.byt nums.cma $(TESTFILES)

test.opt: $(TESTOPTFILES) ..\nums.cmxa ..\libnums.lib
	$(CAMLOPT) -o test.opt nums.cmxa $(TESTOPTFILES)

$(TESTOPTFILES): ..\..\..\ocamlopt

.SUFFIXES: .ml .cmo .cmx

.ml.cmo:
	$(CAMLC) -c $<

.ml.cmx:
	$(CAMLOPT) -c $<

ocamltopnum:
	ocamlmktop -o ocamltopnum -custom ..\nums.cma ..\libnums.lib

clean:
	rm -f test.byt test.opt *.obj *.cm? ocamltopnum

depend:
	ocamldep *.ml > .depend

!include .depend
