CAMLC=..\..\..\boot\ocamlrun ..\..\..\ocamlc -I ..\..\..\stdlib
CAMLOPT=..\..\..\boot\ocamlrun ..\..\..\ocamlopt -I ..\..\..\stdlib

test: test.byt test.opt
	.\test.byt
	.\test.opt

TESTFILES=test.cmo \
  test_nats.cmo test_big_ints.cmo test_ratios.cmo test_nums.cmo end_test.cmo

TESTOPTFILES=$(TESTFILES:.cmo=.cmx)

test.byt: $(TESTFILES) ..\nums.cma ..\libnums.lib
	$(CAMLC) -o test.byt -custom ..\nums.cma $(TESTFILES) ..\libnums.lib

test.opt: $(TESTOPTFILES) ..\nums.cmxa ..\libnums.lib
	$(CAMLOPT) -o test.opt ..\nums.cmxa $(TESTOPTFILES) ..\libnums.lib

$(TESTOPTFILES): ..\..\..\ocamlopt

.SUFFIXES: .ml .cmo .cmx

.ml.cmo:
	$(CAMLC) -I .. -c $<

.ml.cmx:
	$(CAMLOPT) -I .. -c $<

ocamltopnum:
	ocamlmktop -o ocamltopnum -custom ..\nums.cma ..\libnums.lib

clean:
	rm -f test.byt test.opt *.obj *.cm? ocamltopnum

depend:
	ocamldep *.ml > .depend

!include .depend
