!include ..\support\Makefile.common.nt

COMPFLAGS= -I ../support

all: labltkobjs

opt: labltkobjsx

include ./modules

LABLTKOBJS = $(WIDGETOBJS) tk.cmo labltk.cmo
LABLTKOBJSX = $(LABLTKOBJS:.cmo=.cmx)

labltkobjs: $(LABLTKOBJS)

labltkobjsx: $(LABLTKOBJSX)

# All .{ml,mli} files are generated in this directory
clean : 
	rm -f *.cm* *.ml *.mli *.o *.a
	$(MAKE) -f Makefile.gen clean

install: $(LABLTKOBJS)
	@if not exist $(LABLTKDIR) mkdir $(LABLTKDIR)
	cp *.cmi [a-z]*.mli $(LABLTKDIR)

installopt: $(LABLTKOBJSX)
	@if not exist $(LABLTKDIR) mkdir $(LABLTKDIR)
	cp $(LABLTKOBJSX) $(LABLTKDIR)

.SUFFIXES :
.SUFFIXES : .mli .ml .cmi .cmx .cmo .mlp

.mli.cmi:
	$(LABLCOMP) $(COMPFLAGS) $<

.ml.cmo:
	$(LABLCOMP) $(COMPFLAGS) $<

.ml.cmx:
	$(CAMLOPT) -c $(COMPFLAGS) $<

!include .depend
