#!/bin/sh
#**************************************************************************
#*                                                                        *
#*                                 OCaml                                  *
#*                                                                        *
#*            Xavier Leroy, projet Cristal, INRIA Rocquencourt            *
#*                                                                        *
#*   Copyright 2004 Institut National de Recherche en Informatique et     *
#*     en Automatique.                                                    *
#*                                                                        *
#*   All rights reserved.  This file is distributed under the terms of    *
#*   the GNU Lesser General Public License version 2.1, with the          *
#*   special exception on linking described in the file LICENSE.          *
#*                                                                        *
#**************************************************************************

case $1 in
  Stdlib.cm[iox])
      echo ' -nopervasives -no-alias-deps -w -49' \
           ' -pp "$AWK -f ./expand_module_aliases.awk"';;
  # stdlib dependencies
  CamlinternalFormatBasics*.cm[iox]) echo ' -nopervasives';;
  CamlinternalAtomic.cm[iox]) echo ' -nopervasives';;
  # end stdlib dependencies
  CamlinternalOO.cmx) echo ' -inline 0 -afl-inst-ratio 0';;
  CamlinternalLazy.cmx) echo ' -afl-inst-ratio 0';;
    # never instrument camlinternalOO or camlinternalLazy (PR#7725)
  Stdlib__Buffer.cmx) echo ' -inline 3';;
                           # make sure add_char is inlined (PR#5872)
  Stdlib__Buffer.cm[io]) echo ' -w +A';;
  CamlinternalFormat.cm[io]) echo ' -w +A -w -fragile-match';;
  Stdlib__Printf.cm[io]|stdlib__Format.cm[io]|Stdlib__Scanf.cm[io])
      echo ' -w +A -w -fragile-match';;
  Stdlib__Scanf.cmx) echo ' -inline 9';;
  *Labels.cmi) echo ' -pp "$AWK -f ./expand_module_aliases.awk"';;
  *Labels.cm[ox]) echo ' -nolabels -no-alias-deps';;
  Stdlib__Float.cm[ox]) echo ' -nolabels -no-alias-deps';;
  Stdlib__Oo.cmi) echo ' -no-principal';;
    # preserve structure sharing in Oo.copy (PR#9767)
  *) echo ' ';;
esac
