#!/bin/sh
#**************************************************************************
#*                                                                        *
#*                                 OCaml                                  *
#*                                                                        *
#*            Xavier Leroy, projet Cristal, INRIA Rocquencourt            *
#*                                                                        *
#*   Copyright 2004 Institut National de Recherche en Informatique et     *
#*     en Automatique.                                                    *
#*                                                                        *
#*   All rights reserved.  This file is distributed under the terms of    *
#*   the GNU Lesser General Public License version 2.1, with the          *
#*   special exception on linking described in the file LICENSE.          *
#*                                                                        *
#**************************************************************************

case $1 in
  pervasives.cm[iox]) echo ' -nopervasives';;
  camlinternalOO.cmi) echo ' -nopervasives';;
  camlinternalOO.cmx) echo ' -inline 0';;
  buffer.cmx) echo ' -inline 3';;
                           # make sure add_char is inlined (PR#5872)
  buffer.cm[io]) echo ' -w A';;
  camlinternalFormat.cm[io]) echo ' -w Ae';;
  camlinternalFormatBasics.cm[iox]) echo ' -nopervasives';;
  printf.cm[io]|format.cm[io]|scanf.cm[io]) echo ' -w Ae';;
  scanf.cmx) echo ' -inline 9';;
  *Labels.cm[ox]) echo ' -nolabels -no-alias-deps';;
  *) echo ' ';;
esac
