include ../support/Makefile.common.nt

COMPFLAGS=-I ../labltk -I ../support -I $(OTHERS)/win32unix -I $(OTHERS)/str

OBJS= fileselect.cmo balloon.cmo

OBJSX = $(OBJS:.cmo=.cmx)

all: libjpf.cma

opt: libjpf.cmxa

test: balloontest

testopt: balloontest.opt

libjpf.cma: $(OBJS)
	$(CAMLLIBR) -o libjpf.cma $(OBJS)

libjpf.cmxa: $(OBJSX)
	$(CAMLOPTLIBR) -o libjpf.cmxa $(OBJSX)

install: libjpf.cma
	cp $(OBJS:.cmo=.cmi) $(OBJS:.cmo=.mli) libjpf.cma $(INSTALLDIR)

installopt: libjpf.cmxa
	cp libjpf.cmxa libjpf.$(A) $(INSTALLDIR)

clean:
	rm -f *.cm* *.$(O) *.$(A) *~ *test

$(OBJS) $(OBJS:.cmo=.cmi): ../lib/$(LIBNAME).cma

$(OBJSX): ../lib/$(LIBNAME).cmxa

### Tests

balloontest: balloontest.cmo 
	$(CAMLC) -o balloontest -I ../support -I ../labltk -I ../lib \
	        -custom $(LIBNAME).cma libjpf.cma balloontest.cmo $(TKLINKOPT)

balloontest.opt: balloontest.cmx
	$(CAMLOPT) -o balloontest.opt -I ../support -I ../labltk -I ../lib \
	        $(LIBNAME).cmxa libjpf.cmxa balloontest.cmx $(TKLINKOPT)

balloontest.cmo : balloon.cmo libjpf.cma

balloontest.cmx : balloon.cmx libjpf.cmxa

.SUFFIXES :
.SUFFIXES : .mli .ml .cmi .cmx .cmo

.mli.cmi:
	$(CAMLCOMP) $(COMPFLAGS) $<

.ml.cmo:
	$(CAMLCOMP) $(COMPFLAGS) $<

.ml.cmx:
	$(CAMLOPT) -c $(COMPFLAGS) $<

depend: 
	mv Makefile Makefile.bak
	(sed -n -e '1,/^### DO NOT DELETE THIS LINE/p' Makefile.bak; \
	 $(CAMLDEP) *.mli *.ml) > Makefile


### EVERYTHING THAT GOES BEYOND THIS COMMENT IS GENERATED
### DO NOT DELETE THIS LINE
balloon.cmo: balloon.cmi 
balloon.cmx: balloon.cmi 
balloontest.cmo: balloon.cmi 
balloontest.cmx: balloon.cmx 
fileselect.cmo: fileselect.cmi 
fileselect.cmx: fileselect.cmi 
