#**************************************************************************
#*                                                                        *
#*                                 OCaml                                  *
#*                                                                        *
#*                   David Allsopp, Jane Street Europe                    *
#*                                                                        *
#*   Copyright 2026 Jane Street Group LLC                                 *
#*                                                                        *
#*   All rights reserved.  This file is distributed under the terms of    *
#*   the GNU Lesser General Public License version 2.1, with the          *
#*   special exception on linking described in the file LICENSE.          *
#*                                                                        *
#**************************************************************************

ROOTDIR = ..

include $(ROOTDIR)/Makefile.common

cpp:
	@echo $(call QUOTE_SINGLE,$(CPP)) > $@

arch:
	@echo '$(ARCH)' > $@
