#########################################################################
#                                                                       #
#                                 OCaml                                 #
#                                                                       #
#                  Jeremie Dimino, Jane Street Europe                   #
#                                                                       #
#   Copyright 2010 Institut National de Recherche en Informatique et    #
#   en Automatique.  All rights reserved.  This file is distributed     #
#   under the terms of the Q Public License version 1.0.                #
#                                                                       #
#########################################################################

BASEDIR=../..
TOPFLAGS+=-dparsetree
include $(BASEDIR)/makefiles/Makefile.dparsetree
include $(BASEDIR)/makefiles/Makefile.common
