# $Id$

default:
	@for file in *.ml; do \
	  $(OCAML) < $$file > $$file.result 2>&1; \
	  if [ -f $$file.principal.reference ]; then \
	    $(OCAML) -principal < $$file > $$file.principal.result 2>&1; \
	  fi; \
	done
	@for file in *.reference; do \
	  echo -n " ... testing '$$file':"; \
	  diff -q $$file `basename $$file reference`result || (echo " => failed" && exit 1) && echo " => passed"; \
	done

clean: defaultclean
	@rm -f *.result