#########################################################################
#                                                                       #
#                            Objective Caml                             #
#                                                                       #
#            Xavier Leroy, projet Cristal, INRIA Rocquencourt           #
#                                                                       #
#   Copyright 1999 Institut National de Recherche en Informatique et    #
#   en Automatique.  All rights reserved.  This file is distributed     #
#   under the terms of the GNU Library General Public License.          #
#                                                                       #
#########################################################################

# $Id$

include ..\..\config\Makefile.nt

CC=$(BYTECC)
CFLAGS=-I..\..\byterun -I..\win32unix $(BYTECCCOMPOPTS)
CAMLC=..\..\boot\ocamlrun ..\..\ocamlc -I ..\..\stdlib -I ..\win32unix
CAMLOPT=..\..\boot\ocamlrun ..\..\ocamlopt -I ..\..\stdlib -I ..\win32unix

C_OBJS=bigarray_stubs.obj mmap_win32.obj

CAML_OBJS=bigarray.cmo

all: libbigarray.lib bigarray.cma

allopt: libbigarray.lib bigarray.cmxa

libbigarray.lib: $(C_OBJS)
	rm -f libbigarray.lib
	$(MKLIB)libbigarray.lib $(C_OBJS)

bigarray.cma: $(CAML_OBJS)
	$(CAMLC) -a -linkall -custom -o bigarray.cma \
          $(CAML_OBJS) -cclib -lbigarray

bigarray.cmxa: $(CAML_OBJS:.cmo=.cmx)
	$(CAMLOPT) -a -linkall -o bigarray.cmxa \
           $(CAML_OBJS:.cmo=.cmx) -cclib -lbigarray

install:
	cp bigarray.cmi bigarray.mli libbigarray.lib bigarray.cma $(LIBDIR)
	cp bigarray.h $(LIBDIR)/caml/bigarray.h

installopt:
	cp bigarray.lib $(CAML_OBJS:.cmo=.cmx) bigarray.cmxa $(LIBDIR)

partialclean:
	rm -f *.cm*

clean: partialclean
	rm -f libbigarray.lib *.obj

.SUFFIXES: .ml .mli .cmo .cmi .cmx

.mli.cmi:
	$(CAMLC) -c $(COMPFLAGS) $<

.ml.cmo:
	$(CAMLC) -c $(COMPFLAGS) $<

.ml.cmx:
	$(CAMLOPT) -c $(COMPFLAGS) $<

depend:
	gcc -MM $(CFLAGS) *.c > .depend
	..\..\boot\ocamlrun ..\..\tools\ocamldep *.mli *.ml >> .depend

include .depend
