#########################################################################
#                                                                       #
#                                 OCaml                                 #
#                                                                       #
#                 Xavier Clerc, SED, INRIA Rocquencourt                 #
#                                                                       #
#   Copyright 2010 Institut National de Recherche en Informatique et    #
#   en Automatique.  All rights reserved.  This file is distributed     #
#   under the terms of the Q Public License version 1.0.                #
#                                                                       #
#########################################################################

ADD_COMPFLAGS = -pp 'camlp4o'
MAIN_MODULE = camlp4_class_type_plus_ok

include ../../../makefiles/Makefile.okbad
include ../../../makefiles/Makefile.common
