#########################################################################
#                                                                       #
#                            Objective Caml                             #
#                                                                       #
#            Damien Doligez, projet Para, INRIA Rocquencourt            #
#                                                                       #
#   Copyright 1999 Institut National de Recherche en Informatique et    #
#   en Automatique.  All rights reserved.  This file is distributed     #
#   under the terms of the Q Public License version 1.0.                #
#                                                                       #
#########################################################################

# $Id$

start = 0

default Ä ocamlrun.ppc ocamlrun.68k
  :runtest.mpw -start {start} -run ocamlrun.68k tÅ.ml
  #:runtest.mpw -start {start} -run ocamlrun.ppc tÅ.ml

all Ä default
test Ä default

comments Ä
  runtest.mpw -bc tÅ.ml

ocamlrun.ppc Ä :::byterun:ocamlrun no68k.rez
  duplicate -y :::byterun:ocamlrun ocamlrun.ppc
  rez -a no68k.rez -o ocamlrun.ppc

ocamlrun.68k Ä :::byterun:ocamlrun noppc.rez
  duplicate -y :::byterun:ocamlrun ocamlrun.68k
  rez -a noppc.rez -o ocamlrun.68k

clean Ä
  delete -i Å.cm[io] || set status 0
  delete -i a.out
