PROGS=test1.byt test2.byt test3.byt test4.byt test5.byt test6.byt \
  test7.byt test8.byt test9.byt testA.byt sieve.byt \
  testio.byt testsocket.byt testwait.byt testsignal.byt

!include ../../../config/Makefile.nt

all: $(PROGS)

clean:
	rm -f *.cm* *.byt
	rm -f $(PROGS:.byt=.ml)

.SUFFIXES: .ml .byt

{..\..\threads\Tests}.ml{}.byt:
	cp ../../threads/Tests/$*.ml $*.ml
	ocamlc -custom -o $*.byt -I .. -I ../../win32unix unix.cma threads.cma $*.ml ..\libthreads.lib ..\..\win32unix\libunix.lib wsock32.lib

$(PROGS): ../threads.cma ../libthreads.lib ../stdlib.cma
