PROGS=test1.byt test2.byt test3.byt test4.byt test5.byt test6.byt \
  test7.byt test8.byt test9.byt testA.byt sieve.byt \
  testio.byt testsocket.byt testwait.byt testsignal.byt

!include ../../../config/Makefile.nt

CAMLC=..\..\..\boot\ocamlrun ..\..\..\ocamlc -I .. -I ..\..\win32unix -I ..\..\..\stdlib -ccopt /Zi
CAMLOPT=..\..\..\boot\ocamlrun ..\..\..\ocamlopt -I .. -I ..\..\win32unix -I ..\..\..\stdlib

all: $(PROGS)

allopt: $(PROGS:.byt=.out)

clean:
	rm -f *.cm* *.byt *.out
	rm -f $(PROGS:.byt=.ml)

.SUFFIXES: .ml .byt .out

{..\..\threads\Tests}.ml{}.byt:
	cp ../../threads/Tests/$*.ml $*.ml
	$(CAMLC) -custom -o $*.byt unix.cma threads.cma $*.ml ..\libthreads.lib ..\..\win32unix\libunix.lib wsock32.lib

{..\..\threads\Tests}.ml{}.out:
	cp ../../threads/Tests/$*.ml $*.ml
	$(CAMLOPT) -o $*.out unix.cmxa threads.cmxa $*.ml ..\libthreadsnat.lib ..\..\win32unix\libunix.lib wsock32.lib

$(PROGS): ../threads.cma ../libthreads.lib
$(PROGS:.byt=.out): ../threads.cmxa ../libthreadsnat.lib
