#########################################################################
#                                                                       #
#                            Objective Caml                             #
#                                                                       #
#            Xavier Leroy, projet Cristal, INRIA Rocquencourt           #
#                                                                       #
#   Copyright 1999 Institut National de Recherche en Informatique et    #
#   en Automatique.  All rights reserved.  This file is distributed     #
#   under the terms of the GNU Library General Public License, with     #
#   the special exception on linking described in file ../LICENSE.      #
#                                                                       #
#########################################################################

# $Id$

# Configuration for Windows NT/95, Visual C++ 6.0

######### General configuration

PREFIX=C:\ocaml

### Where to install the binaries
BINDIR=$(PREFIX)\bin

### Where to install the standard library
LIBDIR=$(PREFIX)\lib

### Where to install the info files
DISTRIB=$(PREFIX)

### Location of VC++ include files
SYSTEM_INCLUDES=c:\Msdev\VC98\Include

########## Configuration for the bytecode compiler

### Which C compiler to use for the bytecode interpreter.
BYTECC=cl /nologo

### Additional compile-time options for $(BYTECC).  (For static linking.)
BYTECCCOMPOPTS=/Ox /MT

### Additional link-time options for $(BYTECC).  (For static linking.)
BYTECCLINKOPTS=/MT

### Additional compile-time options for $(BYTECC).  (For building a DLL.)
DLLCCCOMPOPTS=/Ox /MD

### Libraries needed
BYTECCLIBS=wsock32.lib
NATIVECCLIBS=wsock32.lib

### How to invoke the C preprocessor
CPP=cl /nologo /EP

### How to invoke the librarian
MKLIB=lib /nologo /debugtype:CV /out:
MKDLL=cl /nologo /MD /LD

############# Configuration for the native-code compiler

### Name of architecture for the native-code compiler
ARCH=i386

### Name of architecture model for the native-code compiler.
MODEL=default

### Name of operating system family for the native-code compiler.
SYSTEM=win32

### Which C compiler to use for the native-code compiler.
NATIVECC=cl /nologo

### Additional compile-time options for $(NATIVECC).
NATIVECCCOMPOPTS=/Ox /MT

### Additional link-time options for $(NATIVECC)
NATIVECCLINKOPTS=/MT

### Flags for the assembler
AS=ml /nologo
AFLAGS=/coff /Cp

############# Configuration for the contributed libraries

OTHERLIBRARIES=win32unix systhreads str num win32graph dynlink bigarray labltk

### Name of the target architecture for the "num" library
BIGNUM_ARCH=C

### Configuration for LablTk
TK_DEFS=-Ic:\Tcl\include
TK_LINK=tk83.lib tcl83.lib

############# Aliases for common commands

MAKEREC=$(MAKE) -nologo -f Makefile.nt 
