!include Makefile.common.nt

all: support.cmo widget.cmo protocol.cmo \
     textvariable.cmo timer.cmo fileevent.cmo \
     liblabltk41.lib

opt: support.cmx widget.cmx protocol.cmx \
     textvariable.cmx timer.cmx fileevent.cmx \
     liblabltk41.lib

COBJS=cltkCaml.obj cltkEval.obj cltkEvent.obj cltkFile.obj cltkMain.obj \
      cltkMisc.obj cltkTimer.obj cltkVar.obj cltkWait.obj

CCFLAGS=-I..\..\..\byterun /Zi $(TK_DEFS)

COMPFLAGS=-I $(OTHERS)/win32unix

liblabltk41.lib : $(COBJS)
	rm -f liblabltk41.lib
	$(MKLIB)liblabltk41.lib $(COBJS)

PUB=fileevent.cmi fileevent.mli \
    protocol.cmi protocol.mli \
    textvariable.cmi textvariable.mli \
    timer.cmi timer.mli \
    widget.cmi widget.mli

install: liblabltk41.lib $(PUB)
	@if not exist $(LABLTKDIR) mkdir $(LABLTKDIR)
	cp $(PUB) $(LABLTKDIR)
	cp liblabltk41.lib $(LABLTKDIR)

clean : 
	rm -f *.cm* *.obj *.lib

.SUFFIXES :
.SUFFIXES : .mli .ml .cmi .cmo .cmx .mlp .c .obj

.mli.cmi:
	$(LABLCOMP) $(COMPFLAGS) $<

.ml.cmo:
	$(LABLCOMP) $(COMPFLAGS) $<

.ml.cmx:
	$(CAMLOPT) -c $(COMPFLAGS) $<

.c.obj:
	$(BYTECC) $(BYTECCCOMPOPTS) $(CCFLAGS) -c $<

depend:
	$(LABLDEP) *.mli *.ml > .depend

$(COBJS): camltk.h

!include .depend
