!include Makefile.common.nt

all: support.cmo rawwidget.cmo widget.cmo protocol.cmo \
     textvariable.cmo timer.cmo fileevent.cmo camltkwrap.cmo \
     dll$(LIBNAME).dll lib$(LIBNAME).lib

opt: support.cmx rawwidget.cmx widget.cmx protocol.cmx \
     textvariable.cmx timer.cmx fileevent.cmx camltkwrap.cmx \
     lib$(LIBNAME).lib

COBJS=cltkCaml.obj cltkUtf.obj cltkEval.obj cltkEvent.obj cltkFile.obj \
   cltkMain.obj cltkMisc.obj cltkTimer.obj cltkVar.obj cltkWait.obj cltkImg.obj

CCFLAGS=-I..\..\..\byterun $(TK_DEFS)

COMPFLAGS=-I $(OTHERS)/win32unix

dll$(LIBNAME).dll : $(COBJS:.obj=.dobj)
	link /nologo /dll /out:dll$(LIBNAME).dll /implib:dll$(LIBNAME).lib \
	  $(COBJS:.obj=.dobj) ..\..\..\byterun\ocamlrun.lib \
          $(TK_LINK) wsock32.lib

lib$(LIBNAME).lib : $(COBJS:.obj=.sobj)
	rm -f lib$(LIBNAME).lib
	$(MKLIB)lib$(LIBNAME).lib $(COBJS:.obj=.sobj)

PUB=fileevent.cmi fileevent.mli \
    protocol.cmi protocol.mli \
    textvariable.cmi textvariable.mli \
    timer.cmi timer.mli \
    rawwidget.cmi rawwidget.mli \
    widget.cmi widget.mli

install: dll$(LIBNAME).dll lib$(LIBNAME).lib $(PUB)
	@if not exist $(INSTALLDIR) mkdir $(INSTALLDIR)
	cp $(PUB) $(INSTALLDIR)
	cp dll$(LIBNAME).dll dll$(LIBNAME).lib lib$(LIBNAME).lib $(INSTALLDIR)
	echo $(INSTALLDIR)>> $(LIBDIR)\ld.conf

clean : 
	rm -f *.cm* *.dobj *.sobj *.dll *.lib *.exp *.obj

.SUFFIXES :
.SUFFIXES : .mli .ml .cmi .cmo .cmx .mlp .c .dobj .sobj

.mli.cmi:
	$(CAMLCOMP) $(COMPFLAGS) $<

.ml.cmo:
	$(CAMLCOMP) $(COMPFLAGS) $<

.ml.cmx:
	$(CAMLOPT) -c $(COMPFLAGS) $<

.c.dobj:
	$(BYTECC) $(DLLCCCOMPOPTS) $(CCFLAGS) -c $<
	mv $*.obj $*.dobj

.c.sobj:
	$(BYTECC) $(BYTECCCOMPOPTS) $(CCFLAGS) -c $<
	mv $*.obj $*.sobj

depend:
	$(CAMLDEP) *.mli *.ml > .depend

$(COBJS): camltk.h

!include .depend
