OTHERSLIB=-I $(OTHERS)/win32unix -I $(OTHERS)/str -I $(OTHERS)/systhreads

CCFLAGS=-I../../../byterun $(TK_DEFS)

include Makefile.shared

ifeq ($(CCOMPTYPE),cc)
WINDOWS_APP=-ccopt "-link -Wl,--subsystem,windows"
else
WINDOWS_APP=-ccopt "-link /subsystem:windows"
endif

XTRAOBJ=winmain.$(O)
XTRALIBS=threads.cma -custom $(WINDOWS_APP)

dummy.mli:
	cp dummyWin.mli dummy.mli
