#########################################################################
#                                                                       #
#                         OCaml LablTk library                          #
#                                                                       #
#            Jacques Garrigue, Kyoto University RIMS                    #
#                                                                       #
#   Copyright 1999 Institut National de Recherche en Informatique et    #
#   en Automatique and Kyoto University.  All rights reserved.          #
#   This file is distributed under the terms of the GNU Library         #
#   General Public License, with the special exception on linking       #
#   described in file ../../../LICENSE.                                 #
#                                                                       #
#########################################################################

# $Id$

OTHERSLIB=-I $(OTHERS)/unix -I $(OTHERS)/str

include Makefile.shared

dummy.mli:
	cp dummyUnix.mli dummy.mli
