OTHERSLIB=-I $(OTHERS)/win32unix -I $(OTHERS)/str -I $(OTHERS)/systhreads

CCFLAGS=-I../../../byterun $(TK_DEFS)

ifeq ($(CCOMPTYPE),cc)
WINDOWS_APP=-ccopt "-Wl,--subsystem,windows"
else
WINDOWS_APP=-ccopt "/link /subsystem:windows"
endif

OCAMLBR=threads.cma winmain.$(O) $(WINDOWS_APP)

dummy.mli:
	cp dummyWin.mli dummy.mli

include Makefile.shared

