#########################################################################
#                                                                       #
#                         OCaml LablTk library                          #
#                                                                       #
#            Jacques Garrigue, Kyoto University RIMS                    #
#                                                                       #
#   Copyright 2000 Institut National de Recherche en Informatique et    #
#   en Automatique and Kyoto University.  All rights reserved.          #
#   This file is distributed under the terms of the GNU Library         #
#   General Public License, with the special exception on linking       #
#   described in file ../../../LICENSE.                                 #
#                                                                       #
#########################################################################

# $Id$

OTHERSLIB=-I $(OTHERS)/win32unix -I $(OTHERS)/str -I $(OTHERS)/systhreads

CCFLAGS=-I../../../byterun $(TK_DEFS)

include ../support/Makefile.common

ifeq ($(CCOMPTYPE),cc)
WINDOWS_APP=-ccopt "-link -Wl,--subsystem,windows"
else
WINDOWS_APP=-ccopt "-link /subsystem:windows"
endif

XTRAOBJ=winmain.$(O)
XTRALIBS=threads.cma -custom $(WINDOWS_APP)

include Makefile.shared

dummy.mli:
	cp dummyWin.mli dummy.mli
