# The lexer generator

CAMLC=..\boot\ocamlrun ..\boot\ocamlc -I ..\boot
COMPFLAGS=
LINKFLAGS=
CAMLYACC=..\boot\ocamlyacc
YACCFLAGS=
CAMLLEX=..\boot\ocamlrun ..\boot\ocamllex
CAMLDEP=..\boot\ocamlrun ..\tools\ocamldep
DEPFLAGS=

OBJS=parser.cmo lexer.cmo lexgen.cmo compact.cmo output.cmo main.cmo

all: ocamllex

ocamllex: $(OBJS)
	$(CAMLC) $(LINKFLAGS) -o ocamllex $(OBJS)

clean::
	rm -f ocamllex
	rm -f *.cmo *.cmi

parser.ml parser.mli: parser.mly
	$(CAMLYACC) $(YACCFLAGS) parser.mly

clean::
	rm -f parser.ml parser.mli

beforedepend:: parser.ml parser.mli

lexer.ml: lexer.mll
	$(CAMLLEX) lexer.mll

clean::
	rm -f lexer.ml

beforedepend:: lexer.ml

.SUFFIXES:
.SUFFIXES: .ml .cmo .mli .cmi

.ml.cmo:
	$(CAMLC) -c $(COMPFLAGS) $<

.mli.cmi:
	$(CAMLC) -c $(COMPFLAGS) $<

depend: beforedepend
	$(CAMLDEP) *.mli *.ml > .depend

!include .depend
