#!/bin/sh

#**************************************************************************
#*                                                                        *
#*                                 OCaml                                  *
#*                                                                        *
#*          Xavier Leroy, projet Cambium, INRIA Paris-Rocquencourt        *
#*                                                                        *
#*   Copyright 2020 Institut National de Recherche en Informatique et     *
#*     en Automatique.                                                    *
#*                                                                        *
#*   All rights reserved.  This file is distributed under the terms of    *
#*   the GNU Lesser General Public License version 2.1, with the          *
#*   special exception on linking described in the file LICENSE.          *
#*                                                                        *
#**************************************************************************

# Test the Dune-based build

set -ex
eval $(opam env)
export LC_ALL=C
git clean -q -f -d -x
./configure
dune build -j2 @libs
