#!/bin/sh

# usage: remove_DEBUG <file>
# remove from <file> every line that contains the string "DEBUG",
# respecting the cpp # line annotation conventions

echo "# 1 \"$1\""
LC_ALL=C sed -e '/DEBUG/s/.*//' "$1"
