#!/bin/sh
# $Id$

case "$1" in
  true) shift
        exec ../boot/ocamlrun  -I ../otherlibs/unix -I ../otherlibs/str \
             ./ocamldoc "$@"
        ;;
     *) shift
        exec ./ocamldoc "$@"
        ;;
esac
