#!/bin/sh

opts=""
libs="$cclibs"
args=$*
rm -f hasgot.c
var="x"
while : ; do
  case "$1" in
    -i) echo "#include <$2>" >> hasgot.c; shift;;
    -t) echo "$2 $var;" >> hasgot.c; var="x$var"; shift;;
    -l*|-L*|-F*) libs="$libs $1";;
    -framework) libs="$libs $1 $2"; shift;;
    -*) opts="$opts $1";;
     *) break;;
  esac
  shift
done

(echo "main() {"
 for f in $*; do echo "  $f();"; done
 echo "}") >> hasgot.c

if test "$verbose" = yes; then
  echo "hasgot $args: $cc $opts -o tst hasgot.c $libs" >&2
  exec $cc $opts -o tst hasgot.c $libs > /dev/null
else
  exec $cc $opts -o tst hasgot.c $libs > /dev/null 2>/dev/null
fi
