(* camlp4r *)
(***********************************************************************)
(*                                                                     *)
(*                             Camlp4                                  *)
(*                                                                     *)
(*        Daniel de Rauglaudre, projet Cristal, INRIA Rocquencourt     *)
(*                                                                     *)
(*  Copyright 2002 Institut National de Recherche en Informatique et   *)
(*  Automatique.  Distributed only by permission.                      *)
(*                                                                     *)
(***********************************************************************)

(* This file has been generated by program: do not edit! *)

val fast : bool ref;;
val no_constructors_arity : bool ref;;
val mkloc : MLast.loc -> Location.t;;
val long_id_of_string_list : MLast.loc -> string list -> Longident.t;;

val str_item : MLast.str_item -> Parsetree.structure -> Parsetree.structure;;
val interf : MLast.sig_item list -> Parsetree.signature;;
val implem : MLast.str_item list -> Parsetree.structure;;
val phrase : MLast.str_item -> Parsetree.toplevel_phrase;;
