#(***********************************************************************)
#(*                                                                     *)
#(*                                OCaml                                *)
#(*                                                                     *)
#(*                   Mark Shinwell, Jane Street Europe                 *)
#(*                                                                     *)
#(*  Copyright 2014 Institut National de Recherche en Informatique et   *)
#(*  en Automatique.  All rights reserved.  This file is distributed    *)
#(*  under the terms of the Q Public License version 1.0.               *)
#(*                                                                     *)
#(***********************************************************************)

BASEDIR=../..
MODULES=
MAIN_MODULE=float_subst_boxed_number
ADD_OPTCOMPFLAGS=-inline 20

include $(BASEDIR)/makefiles/Makefile.one
include $(BASEDIR)/makefiles/Makefile.common
