#########################################################################
#                                                                       #
#                                 OCaml                                 #
#                                                                       #
#            Xavier Leroy, projet Cristal, INRIA Rocquencourt           #
#                                                                       #
#   Copyright 1999 Institut National de Recherche en Informatique et    #
#   en Automatique.  All rights reserved.  This file is distributed     #
#   under the terms of the Q Public License version 1.0.                #
#                                                                       #
#########################################################################

include Makefile.shared

# To make custom toplevels

OCAMLMKTOP=ocamlmktop.cmo
OCAMLMKTOP_IMPORTS=misc.cmo identifiable.cmo numbers.cmo config.cmo clflags.cmo ccomp.cmo

ocamlmktop: $(OCAMLMKTOP)
	$(CAMLC) $(LINKFLAGS) -o ocamlmktop $(OCAMLMKTOP_IMPORTS) $(OCAMLMKTOP)

ocamlmklibconfig.ml:: ../config/Makefile
	echo "let mkdll = try \
                let flexlink = \
                  let flexlink = Sys.getenv \"OCAML_FLEXLINK\" in \
                  let f i = \
                    let c = flexlink.[i] in \
                    if c = '/' then '\\\\' else c in \
                  (String.init (String.length flexlink) f) ^ \" $(FLEXLINK_FLAGS)\" in \
                Printf.sprintf \"%s %s\" flexlink \"$(FLEXLINK_FLAGS)\" \
              with Not_found -> mkdll">> $@

install::
	cp ocamlmktop $(INSTALL_BINDIR)/ocamlmktop$(EXE)

clean::
	rm -f ocamlmktop$(EXE)
