#!/bin/sh

if [ -z "$@" ]; then
   echo "Usage: $0 file.c" 1>&2
   exit 1
fi

sed -E -i.bak '
# Field(x, i) = y ==> Init_field_small(x, i, y)
s/^([ \t]*)Field\(([^;]*),[ \t]*([^;]*)\)[ \t]*=[ \t]*([^;]*);[ \t]*$/\1Init_field_small\(\2, \3, \4\);/

# caml_initialize(&Field(x, i), y) ==> caml_initialize_field(x, i, y)
#     caml_modify(&Field(x, i), y) ==>     caml_modify_field(x, i, y)
s/^([ \t]*)caml_(initialize|modify)[ \t]*\([ \t]*&[ \t]*Field\([ \t]*([^,]*),[ \t]*([^,()]*)[ \t]*\)[ \t]*,/\1caml_\2_field\(\3, \4,/
' "$@"
