#!/bin/sh

# Dual script.  Works under Bourne Shell and MPW Shell.

if : == x
then # Bourne Shell
     exec ocamlc -linkall toplevellib.cma "$@" topmain.cmo
else # MPW Shell
     ocamlc-custom -linkall toplevellib.cma {"parameters"} topmain.cmo
     exit {status}
end
fi
