#!/bin/sh

DELABEL='s/~//g;s/: [a-z_]*:/: /;s/: ([a-z_]*:/: (/;s/ -> [a-z_]*:/ -> /g;s/^\( *\)[a-z_]*:\(.*-\)/\1\2/'
rm -f a b
for i in array bytes list string ; do
  cat stdlib/${i}.mli >> a
  sed -e "$DELABEL" stdlib/${i}Labels.mli >> b
done
cat otherlibs/unix/unix.mli >> a
sed -e "$DELABEL"';s/ = Unix\.[a-zA-Z._]* =/ =/;s/ = Unix\.[a-z_]*$//' otherlibs/unix/unixLabels.mli >> b
sed -e '1,/module Array :/d;/^end/,$d;' stdlib/float.mli >> a
sed -e '1,/module ArrayLabels :/d;/^end/,$d;'"$DELABEL" stdlib/float.mli >> b
for i in hashtbl map set; do
  sed -e '1,15d;s/^./  &/' stdlib/$i.mli >> a
done
sed -e '1,/^module Hashtbl/d;/^module/d;/^$/{N;N;s/\nend\n*//};'"$DELABEL" stdlib/moreLabels.mli >> b
# moreLabels.mli is handled by test_stdlabels.ml
diff -u a b | sed -e '1,2d;/^@@/d;s/ *$//' > tools/labelled-patch-diff
rm -f a b
