#!/usr/bin/env bash
#**************************************************************************
#*                                                                        *
#*                                 OCaml                                  *
#*                                                                        *
#*                            John Whitington                             *
#*                                                                        *
#*   Copyright 2020 Institut National de Recherche en Informatique et     *
#*     en automatique                                                     *
#*                                                                        *
#*   All rights reserved.  This file is distributed under the terms of    *
#*   the GNU Lesser General Public License version 2.1, with the          *
#*   special exception on linking described in the file LICENSE.          *
#*                                                                        *
#**************************************************************************

#Allow to be run from outside tools/
cd $(dirname "$0")/..

if [[ ! -d stdlib || ! -d otherlibs ]] ; then
  echo 'Cannot find the stdlib and otherlibs directories' >&2
  exit 1
fi

#Removes a label, i.e a space, a variable name, followed by a colon followed by
#an alphabetic character or ( or '. This should avoid altering the contents of
#comments.
LABREGEX="s/ [a-z_]+:([a-z\('])/ \1/g"

#A second, sligthly different round sometimes required to deal with f:(key:key
LABLABREGEX="s/\([a-z_]+:([a-z\('])/\(\1/g"

#Remove a tilde if it is followed by some alphanumerics and a space or closing
#OCamldoc code section with ]
TILDEREGEX="s/~([a-z]*[ \]])/\1/g"

#Stdlib
perl -p -e "$LABREGEX" stdlib/listLabels.mli > stdlib/list.temp.mli
perl -p -e "$LABREGEX" stdlib/arrayLabels.mli > stdlib/array.temp.mli
perl -p -e "$LABREGEX" stdlib/stringLabels.mli > stdlib/string.temp.mli
perl -p -e "$LABREGEX" stdlib/bytesLabels.mli > stdlib/bytes.temp.mli

#Stdlib tildes
perl -p -e "$TILDEREGEX" stdlib/list.temp.mli > stdlib/list.mli
perl -p -e "$TILDEREGEX" stdlib/array.temp.mli > stdlib/bytes.mli
perl -p -e "$TILDEREGEX" stdlib/string.temp.mli > stdlib/string.mli
perl -p -e "$TILDEREGEX" stdlib/bytes.temp.mli > stdlib/bytes.mli

#MoreLabels
perl -p -e "$LABREGEX" \
  stdlib/templates/hashtbl.template.mli > stdlib/hashtbl.temp.mli
perl -p -e "$LABLABREGEX" \
  stdlib/hashtbl.temp.mli > stdlib/hashtbl.2temp.mli
perl -p -e "$LABREGEX" \
  stdlib/templates/map.template.mli > stdlib/map.temp.mli
perl -p -e "$LABLABREGEX" \
  stdlib/map.temp.mli > stdlib/map.2temp.mli
perl -p -e "$LABREGEX" \
  stdlib/templates/set.template.mli > stdlib/set.temp.mli
perl -p -e "$LABLABREGEX" \
  stdlib/set.temp.mli > stdlib/set.2temp.mli

#MoreLabels tildes
perl -p -e "$TILDEREGEX" stdlib/hashtbl.2temp.mli > stdlib/hashtbl.mli
perl -p -e "$TILDEREGEX" stdlib/map.2temp.mli > stdlib/map.mli
perl -p -e "$TILDEREGEX" stdlib/set.2temp.mli > stdlib/set.mli

#Substitute the labeled modules in to moreLabels.mli
perl -p -e\
  's/HASHTBL/`tail -n +19 stdlib\/templates\/hashtbl.template.mli`/e' \
  stdlib/templates/moreLabels.template.mli > stdlib/moreLabels.temp.mli
perl -p -e 's/MAP/`tail -n +19 stdlib\/templates\/map.template.mli`/e' \
  stdlib/moreLabels.temp.mli > stdlib/moreLabels.2temp.mli
perl -p -e 's/SET/`tail -n +19 stdlib\/templates\/set.template.mli`/e' \
  stdlib/moreLabels.2temp.mli > stdlib/moreLabels.mli

#Fix up
perl -p -e "s/type statistics =/type statistics = Hashtbl\.statistics =/" \
  stdlib/moreLabels.mli > stdlib/moreLabels.temp.mli
perl -p -e "s/type \(!'a, !'b\) t/type \(!'a, !'b\) t = \('a, 'b) Hashtbl.t/" \
  stdlib/moreLabels.temp.mli > stdlib/moreLabels.2temp.mli
perl -p -e\
  "s/module Make \(H : HashedType\) : S with type key = H.t\
/`cat tools/unlabel-patches/1.mli`/" \
  stdlib/moreLabels.2temp.mli > stdlib/moreLabels.3temp.mli
perl -p -e\
  "s/module MakeSeeded \(H : SeededHashedType\) : SeededS with type key = H.t\
/`cat tools/unlabel-patches/2.mli`/" \
  stdlib/moreLabels.3temp.mli > stdlib/moreLabels.4temp.mli
perl -p -e\
  "s/module Make \(Ord : OrderedType\) : S with type key = Ord.t\
/`cat tools/unlabel-patches/3.mli`/" \
  stdlib/moreLabels.4temp.mli > stdlib/moreLabels.5temp.mli
perl -p -e\
  "s/module Make \(Ord : OrderedType\) : S with type elt = Ord.t\
/`cat tools/unlabel-patches/4.mli`/" \
  stdlib/moreLabels.5temp.mli > stdlib/moreLabels.mli

#Unix
perl -p -e "$LABREGEX" \
  otherlibs/unix/unixLabels.mli > otherlibs/unix/unix.temp.mli
#Tildes
perl -p -e "$TILDEREGEX" \
  otherlibs/unix/unix.temp.mli > otherlibs/unix/unix.mli

#Remove type equivalences from unix.mli

#If one name is a prefix of another, must be after it in this list.
#e.g interval_timer_status and interval_timer
declare -a arr=("error"
                "process_status"
                "wait_flag"
                "file_descr"
                "open_flag"
                "seek_command"
                "file_kind"
                "stats"
                "LargeFile.stats"
                "access_permission"
                "dir_handle"
                "lock_command"
                "sigprocmask_command"
                "process_times"
                "tm"
                "interval_timer_status"
                "interval_timer"
                "passwd_entry"
                "group_entry"
                "inet_addr"
                "socket_domain"
                "socket_type"
                "sockaddr"
                "shutdown_command"
                "msg_flag"
                "host_entry"
                "protocol_entry"
                "service_entry"
                "terminal_io"
                "setattr_when"
                "flush_queue"
                "flow_action"
                "socket_bool_option"
                "socket_int_option"
                "socket_optint_option"
                "socket_float_option"
                "addr_info"
                "getaddrinfo_option"
                "name_info"
                "getnameinfo_option")

for typ in "${arr[@]}"
do
    export typ
    tmpfile=$(mktemp)
    perl -p -e 's/ = Unix.$ENV{'typ'}//' otherlibs/unix/unix.mli > ${tmpfile}
    cat ${tmpfile} > otherlibs/unix/unix.mli
    rm -f ${tmpfile}
done

#Clean up
rm -f stdlib/*temp.mli
rm -f otherlibs/unix/*temp.mli
