!include ..\support\Makefile.common.nt

all: $(LIBNAME).cma

opt: $(LIBNAME).cmxa

clean: 
	rm -f $(LIBNAME).cma $(LIBNAME).cmxa *.lib

!include ..\labltk\modules
LABLTKOBJS=tk.cmo $(WIDGETOBJS)

!include ..\camltk\modules
CAMLTKOBJS=cTk.cmo $(CWIDGETOBJS) labltk.cmo camltk.cmo

SUPPORT=../support/support.cmo ../support/rawwidget.cmo \
	../support/widget.cmo ../support/protocol.cmo \
        ../support/textvariable.cmo ../support/timer.cmo \
        ../support/fileevent.cmo ../support/camltkwrap.cmo

TKOBJS=$(SUPPORT) $(LABLTKOBJS) $(CAMLTKOBJS)

TOPDEPS = $(TOPDIR)/toplevel/toplevellib.cma $(TOPDIR)/toplevel/topmain.cmo

$(LIBNAME).cma: $(SUPPORT)
	cd ..\labltk & $(MAKEREC)
	cd ..\camltk & $(MAKEREC)
	$(CAMLLIBR) -o $(LIBNAME).cma -I ../labltk -I ../camltk $(TKOBJS) \
	  -dllib -l$(LIBNAME) -cclib -l$(LIBNAME) $(TK_LINK)

$(LIBNAME).cmxa: $(SUPPORT:.cmo=.cmx)
	cd ../labltk; $(MAKEREC) opt
	cd ../camltk; $(MAKEREC) opt
	$(CAMLOPTLIBR) -o $(LIBNAME).cmxa -I ../labltk -I ../camltk \
	  $(TKOBJS:.cmo=.cmx) -cclib -l$(LIBNAME) $(TK_LINK)

# $(LIBNAME)top$(EXE) : $(TOPDEPS) $(LIBNAME).cma ../support/lib$(LIBNAME).a
# 	$(CAMLC) -linkall -o $(LIBNAME)top$(EXE) -I ../support \
# 	       -I $(TOPDIR)/toplevel toplevellib.cma \
# 	       -I ../labltk -I ../camltk $(LIBNAME).cma \
# 	       -I $(OTHERS)/unix unix.cma \
# 	       -I $(OTHERS)/str str.cma \
# 	       $(DLLPATH) \
# 	       topmain.cmo
# 
# $(LIBNAME): Makefile $(TOPDIR)/config/Makefile
# 	@echo Generate $@
# 	@echo "#!/bin/sh" > $@
# 	@echo 'exec $(INSTALLDIR)/$(LIBNAME)top$(EXE) -I $(INSTALLDIR) $$*' >> $@

install: all
	@if not exist $(INSTALLDIR) mkdir $(INSTALLDIR)
	cp $(LIBNAME).cma $(INSTALLDIR)
#	@if test -d $(BINDIR); then : ; else mkdir $(BINDIR); fi
#	cp $(LIBNAME) $(BINDIR)

installopt: opt
	@if not exist $(INSTALLDIR) mkdir $(INSTALLDIR)
	cp $(LIBNAME).cmxa $(LIBNAME).lib $(INSTALLDIR)
