BASEDIR=../..
MODULES=testing misc
INCLUDES= -I $(TTOP)/utils
ADD_COMPFLAGS=$(INCLUDES)
CMO_FILES+="misc.cmo"

include $(BASEDIR)/makefiles/Makefile.several
include $(BASEDIR)/makefiles/Makefile.common
