#**************************************************************************
#*                                                                        *
#*                                 OCaml                                  *
#*                                                                        *
#*            Xavier Leroy, projet Cristal, INRIA Rocquencourt            *
#*                                                                        *
#*   Copyright 1999 Institut National de Recherche en Informatique et     *
#*     en Automatique.                                                    *
#*                                                                        *
#*   All rights reserved.  This file is distributed under the terms of    *
#*   the GNU Lesser General Public License version 2.1, with the          *
#*   special exception on linking described in the file LICENSE.          *
#*                                                                        *
#**************************************************************************

include Makefile.shared

ifdef BOOTSTRAPPING_FLEXLINK
MAKE_OCAMLRUN=$(MKEXE_BOOT)
else
MAKE_OCAMLRUN=$(MKEXE) -o $(1) $(2)
endif

ocamlrun$(EXE): libcamlrun.$(A) prims.$(O)
	$(call MAKE_OCAMLRUN,ocamlrun$(EXE),prims.$(O) libcamlrun.$(A) \
	         $(call SYSLIB,ws2_32) $(EXTRALIBS))

ocamlrund$(EXE): libcamlrund.$(A) prims.$(O) main.$(O)
	$(MKEXE) -o ocamlrund$(EXE) prims.$(O) \
	         $(call SYSLIB,ws2_32) $(EXTRALIBS) libcamlrund.$(A)

.depend.nt: .depend
	rm -f .depend.win32
	echo "win32.o: win32.c caml/fail.h caml/compatibility.h \\"\
	  >> .depend.win32
	echo " caml/misc.h caml/config.h ../config/m.h ../config/s.h \\"\
	  >> .depend.win32
	echo " caml/mlvalues.h caml/memory.h caml/gc.h caml/major_gc.h \\"\
	  >> .depend.win32
	echo " caml/freelist.h caml/minor_gc.h caml/osdeps.h caml/signals.h"\
	  >> .depend.win32
	cat .depend >> .depend.win32
	sed -ne '/\.pic\.o/q' \
	    -e 's/^\(.*\)\.d\.o:/\1.$$(DBGO):/' \
	    -e 's/^\(.*\)\.o:/\1.$$(O):/' \
	    -e p \
	    .depend.win32 > .depend.nt
	rm -f .depend.win32

include .depend.nt
