MODULES=syntax gram_aux grammar scan_aux scanner lexgen output
MAIN_MODULE=main
LEX_MODULES=scanner
YACC_MODULES=grammar
ADD_COMPFLAGS=-w a
EXEC_ARGS=input

include ../../makefiles/Makefile.one
include ../../makefiles/Makefile.common
