#**************************************************************************
#*                                                                        *
#*                                 OCaml                                  *
#*                                                                        *
#*            Xavier Leroy, projet Cristal, INRIA Rocquencourt            *
#*                                                                        *
#*   Copyright 1999 Institut National de Recherche en Informatique et     *
#*     en Automatique.                                                    *
#*                                                                        *
#*   All rights reserved.  This file is distributed under the terms of    *
#*   the GNU Lesser General Public License version 2.1, with the          *
#*   special exception on linking described in the file LICENSE.          *
#*                                                                        *
#**************************************************************************

include ../config/Makefile

include Makefile.shared

CC=$(NATIVECC)
CFLAGS=-I../byterun -DNATIVE_CODE -DTARGET_$(ARCH) -DSYS_$(SYSTEM) \
       $(NATIVECCCOMPOPTS) $(IFLEXDIR)

ifeq ($(TOOLCHAIN),mingw)
ASMOBJS=$(ARCH).o
else
ASMOBJS=$(ARCH)nt.obj
endif

OBJS=$(COBJS) $(ASMOBJS)

all: libasmrun.$(A)

libasmrun.$(A): $(OBJS)
	$(call MKLIB,libasmrun.$(A), $(OBJS))

i386nt.obj: i386nt.asm
	$(ASM)i386nt.obj i386nt.asm

amd64nt.obj: amd64nt.asm
	$(ASM)amd64nt.obj amd64nt.asm

i386.o: i386.S
	$(ASPP) -DSYS_$(SYSTEM) i386.S

amd64.o: amd64.S
	$(ASPP) -DSYS_$(SYSTEM) amd64.S

INSTALL_LIBDIR=$(DESTDIR)$(LIBDIR)

install:
	cp libasmrun.$(A) "$(INSTALL_LIBDIR)"

$(LINKEDFILES): %.c: ../byterun/%.c
	cp ../byterun/$*.c $*.c

# Need special compilation rule so as not to do -I../byterun
#win32.$(O): ../byterun/win32.c
#	$(CC) -c $(NATIVECCCOMPOPTS) -DNATIVE_CODE $(IFLEXDIR) \
#	      ../byterun/win32.c

%.$(O): %.c
	$(CC) $(CFLAGS) -c $<

clean::
	rm -f $(LINKEDFILES)

clean::
	rm -f *.$(O) *.$(A) *~

.depend.nt: .depend
	sed -e 's/\.o/.$(O)/g' .depend > .depend.nt

include .depend.nt
